"""Styled .ass captions for vertical shorts (1080x1920), burned via libass.

Two modes:
- karaoke-highlight: word groups, active word tinted+scaled via override tags
  (more reliable than karaoke \\k, full control per word);
- word-carousel: one word at a time, centered, 80->100 pop via \\t().

Timings come from a words.json ([{word, start, end}]); style is a small
validated dict. Pure stdlib — no dependencies.
"""
import json, re

PLAY_X, PLAY_Y = 1080, 1920
DEFAULTS = {"font": "Liberation Sans", "fontSize": 88, "primaryColor": "#FFFFFF",
            "highlightColor": "#FFE600", "outline": 4, "maxWordsPerGroup": 4,
            "bold": True, "uppercase": False}

def _hex(h):
    h = h.lstrip("#").strip()
    if len(h) == 3: h = "".join(c + c for c in h)
    if not re.fullmatch(r"[0-9a-fA-F]{6}", h): raise ValueError(f"bad color {h!r}")
    return (h[4:6] + h[2:4] + h[0:2]).upper()

def _style_color(h, alpha=0):
    """&HAABBGGRR — alpha 0 = opaque, 255 = transparent."""
    return f"&H{max(0, min(255, int(alpha))):02X}{_hex(h)}"
def _ovr_color(h): return f"&H{_hex(h)}&"

def _t(t):
    cs = max(0, round(t * 100))
    return f"{cs//360000}:{(cs%360000)//6000:02d}:{(cs%6000)//100:02d}.{cs%100:02d}"

def _esc(s): return re.sub(r"\s+", " ", re.sub(r"[{}\\\\]", "", s)).strip()

def _groups(words, max_words, max_chars=30):
    out, cur, ln = [], [], 0
    for w in words:
        wl = len(w["word"])
        if cur and (len(cur) >= max_words or ln + 1 + wl > max_chars):
            out.append(cur); cur, ln = [], 0
        cur.append(w); ln += (1 if ln else 0) + wl
    if cur: out.append(cur)
    return out

def _header(st, position):
    align = {"top": 8, "center": 5}.get(position, 2)
    # bottom keeps above the lower 25% (Reels/TikTok UI); top clears the top 13%
    default_v = {"top": round(PLAY_Y * 0.13), "center": 0}.get(position, round(PLAY_Y * 0.25))
    margin_v = int(st.get("marginV", default_v))
    box = st.get("box")
    if box:
        # BorderStyle 3: an opaque box behind each line; libass paints it with
        # OutlineColour and pads it by Outline
        b = box if isinstance(box, dict) else {}
        alpha = round(255 * (1 - float(b.get("opacity", 0.85))))
        outline_colour = _style_color(b.get("color", "#000000"), alpha)
        border_style, outline, shadow = 3, int(b.get("padding", 16)), 0
    else:
        outline_colour = _style_color(st.get("outlineColor", "#000000"))
        border_style, outline, shadow = 1, st["outline"], 2
    return "\n".join([
        "[Script Info]", "; generated by ass_captions.py (sanctioned route)",
        "ScriptType: v4.00+", f"PlayResX: {PLAY_X}", f"PlayResY: {PLAY_Y}",
        "WrapStyle: 0", "ScaledBorderAndShadow: yes", "YCbCr Matrix: TV.709", "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        f"Style: Default,{st['font']},{st['fontSize']},{_style_color(st['primaryColor'])},{_style_color(st['primaryColor'])},{outline_colour},&H80000000,{-1 if st['bold'] else 0},0,0,0,100,100,0,0,{border_style},{outline},{shadow},{align},80,80,{margin_v},1",
        "", "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ])

def _dlg(s, e, text): return f"Dialogue: 0,{_t(s)},{_t(max(e, s + 0.01))},Default,,0,0,0,,{text}"

def build_ass(words, mode, style=None):
    st = {**DEFAULTS, **(style or {})}
    position = st.get("position") or ("center" if mode == "word-carousel" else "bottom")
    up = (lambda x: x.upper()) if st.get("uppercase") else (lambda x: x)
    ws = sorted(({**w, "word": up(_esc(w["word"]))} for w in words if _esc(w["word"])), key=lambda w: w["start"])
    if not ws: raise ValueError("no words")
    lines = []
    if mode == "karaoke-highlight":
        hl, prim = _ovr_color(st["highlightColor"]), _ovr_color(st["primaryColor"])
        # a group must fit one line: the usable width (canvas minus side margins and
        # the box padding) over an average glyph width — caps take ~0.58 em (measured on
        # Montserrat Bold), mixed case ~0.5, +10% for the scaled-up active word
        em = float(st["fontSize"]) * (0.58 if st.get("uppercase") else 0.5) * 1.1
        max_chars = max(8, min(30, int((PLAY_X - 160 - 40) / em)))
        for g in _groups(ws, st["maxWordsPerGroup"], max_chars):
            for i in range(len(g)):
                end = g[i + 1]["start"] if i < len(g) - 1 else g[-1]["end"]
                text = " ".join(
                    (f"{{\\c{hl}\\fscx110\\fscy110}}{w['word']}{{\\c{prim}\\fscx100\\fscy100}}" if j == i else w["word"])
                    for j, w in enumerate(g))
                lines.append(_dlg(g[i]["start"], end, text))
    elif mode == "word-carousel":
        for i, w in enumerate(ws):
            end = max(w["end"], ws[i + 1]["start"]) if i + 1 < len(ws) else w["end"]
            lines.append(_dlg(w["start"], end, f"{{\\fscx80\\fscy80\\t(0,80,\\fscx100\\fscy100)}}{w['word']}"))
    else:
        raise ValueError(f"unknown mode {mode!r} (karaoke-highlight | word-carousel)")
    return _header(st, position) + "\n" + "\n".join(lines) + "\n"
