"""Styled .ass captions for shorts, burned via libass.

Canonical home: github.com/nik-devs/ffmpeg-caption-burn-ass (vendored here). Three modes:
- karaoke-highlight: word groups, active word tinted+scaled via override tags
  (more reliable than karaoke \\k, full control per word);
- word-carousel: one word at a time, centered, 80->100 pop via \\t();
- phrases: one given phrase per event, exactly its [start, end], on a
  rounded plate (colour, opacity, radius, padding) sized to the text.

The canvas is 1080 wide and as tall as the video's aspect (1920 for 9:16):
libass scales it onto the real frame, so a square or 16:9 video is not stretched.

This is the SANCTIONED generated-.ass route: timings come from words.json,
style from a validated schema. The GATES ban on HAND-WRITTEN .ass stands.
"""
import json, math, re, subprocess

PLAY_X, PLAY_Y = 1080, 1920
DEFAULTS = {"font": "Liberation Sans", "fontSize": 88, "primaryColor": "#FFFFFF",
            "highlightColor": "#FFE600", "outline": 4, "maxWordsPerGroup": 4,
            "bold": True, "uppercase": False}

def _hex(h):
    h = h.lstrip("#").strip()
    if len(h) == 3: h = "".join(c + c for c in h)
    if not re.fullmatch(r"[0-9a-fA-F]{6}", h): raise ValueError(f"bad color {h!r}")
    return (h[4:6] + h[2:4] + h[0:2]).upper()

def _style_color(h, alpha=0):
    """&HAABBGGRR — alpha 0 = opaque, 255 = transparent."""
    return f"&H{max(0, min(255, int(alpha))):02X}{_hex(h)}"
def _ovr_color(h): return f"&H{_hex(h)}&"

def _t(t):
    cs = max(0, round(t * 100))
    return f"{cs//360000}:{(cs%360000)//6000:02d}:{(cs%6000)//100:02d}.{cs%100:02d}"

# [laughs] / [whispers] / *sighs* — voice-performance tags from a TTS script, never shown
def _esc(s): return re.sub(r"\s+", " ", re.sub(r"[{}\\\\]", "", re.sub(r"\[[^\]]*\]|\*[^*]*\*", "", s))).strip()

def _groups(words, max_words, max_chars=30):
    out, cur, ln = [], [], 0
    for w in words:
        wl = len(w["word"])
        if cur and (len(cur) >= max_words or ln + 1 + wl > max_chars):
            out.append(cur); cur, ln = [], 0
        cur.append(w); ln += (1 if ln else 0) + wl
    if cur: out.append(cur)
    return out

def _header(st, position, play_y=PLAY_Y):
    align = {"top": 8, "center": 5}.get(position, 2)
    # bottom keeps above the lower 25% (Reels/TikTok UI); top clears the top 13%
    default_v = {"top": round(play_y * 0.13), "center": 0}.get(position, round(play_y * 0.25))
    margin_v = int(st.get("marginV", default_v))
    box = st.get("box")
    if box:
        # BorderStyle 3: an opaque box behind each line; libass paints it with
        # OutlineColour and pads it by Outline
        b = box if isinstance(box, dict) else {}
        alpha = round(255 * (1 - float(b.get("opacity", 0.85))))
        outline_colour = _style_color(b.get("color", "#000000"), alpha)
        border_style, outline, shadow = 3, int(b.get("padding", 16)), 0
    else:
        outline_colour = _style_color(st.get("outlineColor", "#000000"))
        border_style, outline, shadow = 1, st["outline"], 2
    return "\n".join([
        "[Script Info]", "; generated by ass_captions.py (sanctioned route)",
        "ScriptType: v4.00+", f"PlayResX: {PLAY_X}", f"PlayResY: {play_y}",
        "WrapStyle: 0", "ScaledBorderAndShadow: yes", "YCbCr Matrix: TV.709", "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        f"Style: Default,{st['font']},{st['fontSize']},{_style_color(st['primaryColor'])},{_style_color(st['primaryColor'])},{outline_colour},&H80000000,{-1 if st['bold'] else 0},0,0,0,100,100,0,0,{border_style},{outline},{shadow},{align},80,80,{margin_v},1",
        "", "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ])

def _dlg(s, e, text, layer=0): return f"Dialogue: {layer},{_t(s)},{_t(max(e, s + 0.01))},Default,,0,0,0,,{text}"


# --- phrases: text measured with the real font, plate drawn to fit it ---

def _font_path(family, bold, font_dirs=()):
    """The file libass will use for `family`: a passed font first, else fontconfig."""
    from PIL import ImageFont
    import os
    want = family.lower()
    for d in font_dirs:
        for n in sorted(os.listdir(d)):
            if n.lower().endswith((".ttf", ".otf")):
                try:
                    fam, sty = ImageFont.truetype(os.path.join(d, n), 20).getname()
                except OSError:
                    continue
                if fam.lower() == want and (("bold" in sty.lower()) == bool(bold) or not bold):
                    return os.path.join(d, n)
    q = f"{family}:{'bold' if bold else 'regular'}"
    return subprocess.run(["fc-match", "-f", "%{file}", q], capture_output=True, text=True, check=True).stdout.strip()

def _measurer(path, font_size):
    """Text metrics in canvas units at libass's size. libass sets the font so that
    ascent+descent == Fontsize, PIL sizes by em — scale between the two.
    Returns (width_of, ascent, cap_height)."""
    from PIL import ImageFont
    probe = ImageFont.truetype(path, 200)
    asc, desc = probe.getmetrics()
    k = font_size / (asc + desc)
    cap = -probe.getbbox("H", anchor="ls")[1] * k
    return (lambda text: probe.getlength(text) * k), asc * k, cap

def _wrap(text, width_of, max_w):
    lines, cur = [], ""
    for w in text.split():
        nxt = f"{cur} {w}".strip()
        if cur and width_of(nxt) > max_w:
            lines.append(cur); cur = w
        else:
            cur = nxt
    if cur: lines.append(cur)
    return lines

def _rounded_rect(w, h, r):
    """ASS drawing of a w x h rectangle with corner radius r, origin top-left."""
    r = max(0, min(r, w / 2, h / 2))
    c = r * 0.5523  # cubic bezier circle approximation
    f = lambda v: f"{v:.1f}".rstrip("0").rstrip(".")
    return " ".join([
        f"m {f(r)} 0", f"l {f(w - r)} 0",
        f"b {f(w - r + c)} 0 {f(w)} {f(r - c)} {f(w)} {f(r)}", f"l {f(w)} {f(h - r)}",
        f"b {f(w)} {f(h - r + c)} {f(w - r + c)} {f(h)} {f(w - r)} {f(h)}", f"l {f(r)} {f(h)}",
        f"b {f(r - c)} {f(h)} 0 {f(h - r + c)} 0 {f(h - r)}", f"l 0 {f(r)}",
        f"b 0 {f(r - c)} {f(r - c)} 0 {f(r)} 0",
    ])

PHRASE_DEFAULTS = {"font": "Liberation Sans", "fontSize": 64, "primaryColor": "#000000", "bold": True,
                   "plate": {"color": "#FFFFFF", "opacity": 1.0, "radius": 28, "padX": 36, "padY": 20},
                   "maxWidth": 0.84, "lineSpacing": 1.15}

def _phrases(phrases, st, position, play_y, font_dirs):
    plate = {**PHRASE_DEFAULTS["plate"], **(st.get("plate") or {})}
    size = float(st["fontSize"])
    width_of, ascent, cap = _measurer(_font_path(st["font"], st["bold"], font_dirs), size)
    max_w = PLAY_X * float(st.get("maxWidth", 0.84)) - 2 * plate["padX"]
    # every line is its own event on its own baseline, so spacing is ours, not
    # libass's; the plate is centred on the CAPITALS (cap top .. baseline) —
    # centring the whole line box left the text riding high, descenders hang
    # into the bottom padding as in any designed caption
    step = size * float(st.get("lineSpacing", 1.15))
    default_v = {"top": round(play_y * 0.13), "center": 0}.get(position, round(play_y * 0.25))
    margin_v = int(st.get("marginV", default_v))
    alpha = round(255 * (1 - float(plate["opacity"])))
    fill = f"\\1c{_ovr_color(plate['color'])}\\1a&H{alpha:02X}&\\bord0\\shad0"
    out = []
    for ph in sorted(phrases, key=lambda p: p["start"]):
        text = _esc(ph["text"])
        if st.get("uppercase"): text = text.upper()
        if not text: continue
        lines = _wrap(text, width_of, max_w)
        w = max(width_of(l) for l in lines) + 2 * plate["padX"]
        h = cap + step * (len(lines) - 1) + 2 * plate["padY"]
        cx = PLAY_X / 2
        # anchor: bottom edge margin_v above the frame bottom (top/center likewise)
        top = {"top": margin_v, "center": (play_y - h) / 2}.get(position, play_y - margin_v - h)
        box = f"{{\\an7\\pos({cx - w / 2:.1f},{top:.1f}){fill}\\p1}}{_rounded_rect(w, h, plate['radius'])}"
        out.append(_dlg(ph["start"], ph["end"], box, 0))
        for i, line in enumerate(lines):
            baseline = top + plate["padY"] + cap + i * step
            # \an8 anchors the line box top, which sits `ascent` above the baseline
            out.append(_dlg(ph["start"], ph["end"], f"{{\\an8\\pos({cx:.1f},{baseline - ascent:.1f})\\bord0\\shad0}}{line}", 1))
    return out

def build_ass(words, mode, style=None, *, phrases=None, video_size=None, font_dirs=()):
    """words: [{word,start,end}] for the word modes; phrases: [{text,start,end}] for
    mode "phrases". video_size (w, h) sets the canvas aspect."""
    play_y = round(PLAY_X * video_size[1] / video_size[0]) if video_size else PLAY_Y
    if mode == "phrases":
        st = {**DEFAULTS, **PHRASE_DEFAULTS, **(style or {})}
        position = st.get("position") or "bottom"
        if not phrases: raise ValueError("mode phrases needs phrases: [{text, start, end}]")
        lines = _phrases(phrases, st, position, play_y, font_dirs)
        if not lines: raise ValueError("no phrase text")
        return _header({**st, "outline": 0}, position, play_y) + "\n" + "\n".join(lines) + "\n"
    st = {**DEFAULTS, **(style or {})}
    position = st.get("position") or ("center" if mode == "word-carousel" else "bottom")
    up = (lambda x: x.upper()) if st.get("uppercase") else (lambda x: x)
    ws = sorted(({**w, "word": up(_esc(w["word"]))} for w in words if _esc(w["word"])), key=lambda w: w["start"])
    if not ws: raise ValueError("no words")
    lines = []
    if mode == "karaoke-highlight":
        hl, prim = _ovr_color(st["highlightColor"]), _ovr_color(st["primaryColor"])
        # a group must fit one line: the usable width (canvas minus side margins and
        # the box padding) over an average glyph width — caps take ~0.58 em (measured on
        # Montserrat Bold), mixed case ~0.5, +10% for the scaled-up active word
        em = float(st["fontSize"]) * (0.58 if st.get("uppercase") else 0.5) * 1.1
        max_chars = max(8, min(30, int((PLAY_X - 160 - 40) / em)))
        for g in _groups(ws, st["maxWordsPerGroup"], max_chars):
            for i in range(len(g)):
                end = g[i + 1]["start"] if i < len(g) - 1 else g[-1]["end"]
                text = " ".join(
                    (f"{{\\c{hl}\\fscx110\\fscy110}}{w['word']}{{\\c{prim}\\fscx100\\fscy100}}" if j == i else w["word"])
                    for j, w in enumerate(g))
                lines.append(_dlg(g[i]["start"], end, text))
    elif mode == "word-carousel":
        for i, w in enumerate(ws):
            end = max(w["end"], ws[i + 1]["start"]) if i + 1 < len(ws) else w["end"]
            lines.append(_dlg(w["start"], end, f"{{\\fscx80\\fscy80\\t(0,80,\\fscx100\\fscy100)}}{w['word']}"))
    else:
        raise ValueError(f"unknown mode {mode!r} (karaoke-highlight | word-carousel | phrases)")
    return _header(st, position, play_y) + "\n" + "\n".join(lines) + "\n"
