"""Styled .ass captions for vertical shorts (1080x1920), burned via libass.

Two modes:
- karaoke-highlight: word groups, active word tinted+scaled via override tags
  (more reliable than karaoke \\k, full control per word);
- word-carousel: one word at a time, centered, 80->100 pop via \\t().

Timings come from a words.json ([{word, start, end}]); style is a small
validated dict. Pure stdlib — no dependencies.
"""
import json, re

PLAY_X, PLAY_Y = 1080, 1920
DEFAULTS = {"font": "Liberation Sans", "fontSize": 88, "primaryColor": "#FFFFFF",
            "highlightColor": "#FFE600", "outline": 4, "maxWordsPerGroup": 4}

def _hex(h):
    h = h.lstrip("#").strip()
    if len(h) == 3: h = "".join(c + c for c in h)
    if not re.fullmatch(r"[0-9a-fA-F]{6}", h): raise ValueError(f"bad color {h!r}")
    return (h[4:6] + h[2:4] + h[0:2]).upper()

def _style_color(h): return f"&H00{_hex(h)}"
def _ovr_color(h): return f"&H{_hex(h)}&"

def _t(t):
    cs = max(0, round(t * 100))
    return f"{cs//360000}:{(cs%360000)//6000:02d}:{(cs%6000)//100:02d}.{cs%100:02d}"

def _esc(s): return re.sub(r"\s+", " ", re.sub(r"[{}\\\\]", "", s)).strip()

def _groups(words, max_words, max_chars=30):
    out, cur, ln = [], [], 0
    for w in words:
        wl = len(w["word"])
        if cur and (len(cur) >= max_words or ln + 1 + wl > max_chars):
            out.append(cur); cur, ln = [], 0
        cur.append(w); ln += (1 if ln else 0) + wl
    if cur: out.append(cur)
    return out

def _header(st, position):
    align = 5 if position == "center" else 2
    margin_v = 0 if position == "center" else round(PLAY_Y * 0.25)
    return "\n".join([
        "[Script Info]", "; generated by ass_captions.py (sanctioned route)",
        "ScriptType: v4.00+", f"PlayResX: {PLAY_X}", f"PlayResY: {PLAY_Y}",
        "WrapStyle: 2", "ScaledBorderAndShadow: yes", "YCbCr Matrix: TV.709", "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        f"Style: Default,{st['font']},{st['fontSize']},{_style_color(st['primaryColor'])},{_style_color(st['primaryColor'])},&H00000000,&H80000000,1,0,0,0,100,100,0,0,1,{st['outline']},2,{align},80,80,{margin_v},1",
        "", "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ])

def _dlg(s, e, text): return f"Dialogue: 0,{_t(s)},{_t(max(e, s + 0.01))},Default,,0,0,0,,{text}"

def build_ass(words, mode, style=None):
    st = {**DEFAULTS, **(style or {})}
    position = st.get("position") or ("center" if mode == "word-carousel" else "bottom")
    ws = sorted(({**w, "word": _esc(w["word"])} for w in words if _esc(w["word"])), key=lambda w: w["start"])
    if not ws: raise ValueError("no words")
    lines = []
    if mode == "karaoke-highlight":
        hl, prim = _ovr_color(st["highlightColor"]), _ovr_color(st["primaryColor"])
        for g in _groups(ws, st["maxWordsPerGroup"]):
            for i in range(len(g)):
                end = g[i + 1]["start"] if i < len(g) - 1 else g[-1]["end"]
                text = " ".join(
                    (f"{{\\c{hl}\\fscx110\\fscy110}}{w['word']}{{\\c{prim}\\fscx100\\fscy100}}" if j == i else w["word"])
                    for j, w in enumerate(g))
                lines.append(_dlg(g[i]["start"], end, text))
    elif mode == "word-carousel":
        for i, w in enumerate(ws):
            end = max(w["end"], ws[i + 1]["start"]) if i + 1 < len(ws) else w["end"]
            lines.append(_dlg(w["start"], end, f"{{\\fscx80\\fscy80\\t(0,80,\\fscx100\\fscy100)}}{w['word']}"))
    else:
        raise ValueError(f"unknown mode {mode!r} (karaoke-highlight | word-carousel)")
    return _header(st, position) + "\n" + "\n".join(lines) + "\n"
